### ISSUE TITLE
new vision magazine for 2018

### ISSUE THREAD

**Issue by sahiti-enjeti** [gwu-libraries/lai-drupal#24]
the current vision magazine on the LAI website is from 2017 - it needs to be updated 

https://library.gwu.edu/vision/2017

**Comment by maxstarkenburg** [comment]
@rdelaloy, do we know if this year's is going on the LAI site like last time, and if so whether it'll be at the same URL (and thus presumably need to move to the past issue currently at https://lai.gwu.edu/magazine to a different alias, and maybe we'll also need to create some linkage to past issues)?

**Comment by maxstarkenburg** [comment]
So this is pretty much done, and I've even updated https://lai.gwu.edu/vision-magazine-issues with covers/links to the older copies on libsite, though I stopped short of unpublishing https://library.gwu.edu/vision-magazine partly out of laziness to update the 3 other pages that link there, and partly because I'm not sure if we're supposed to somehow still link to "Library Update" (as that page does) from somewhere on libsite or lai?

**Comment by rdelaloy** [comment]
Its so pretty! Library Update is now 1000 years old and we won't do it again so nothing needs to link to it. 

Will there be a link to https://lai.gwu.edu/vision-magazine-issues on the Vision 2019 page? Any place else? Its so pretty; I want people to see it.

**Comment by maxstarkenburg** [comment]
There's already a link to it ("Go to past issues") from the 2019 page. The 2018 page(s) don't have a link back there. Do you want me to change the 2015 through 2017 pages on libsite that currently link back to https://library.gwu.edu/vision-magazine to go to https://lai.gwu.edu/vision-magazine-issues instead and then unpublish the former?

**Comment by rdelaloy** [comment]
Sorry - I totally missed the 2019 link. Yes, please add a link to all of the past issues and then get rid of https://library.gwu.edu/vision-magazine

**Comment by maxstarkenburg** [comment]
Ok, I updated the older issues' pages to go to the lai page, and instead of unpublishing libsite/vision-magazine it occurred to me that I could just redirect that page to lai too, so did that just in case any external sites out there currently link libsite/vision-magazine. Closing.
