### ISSUE TITLE
Somers Hall photos are inaccurate

### ISSUE THREAD

**Issue by maxstarkenburg** [gwu-libraries/lai-drupal#25]
Well, one of them is. On https://studyspaces.gwu.edu/, if you switch to Mount Vernon, and filter by Location choosing Somers Hall, you'll notice that they both use the same exact photo. I don't know if it's the 2nd or 3rd floor in the photo, nor do I know who would know, and who could take a new photo of the other space, but I also can't imagine it's the best use of resources to go over there myself.

**Comment by qbaron** [comment]
Looks like we have photos of both spaces but it's not clear from the folder structure which is which. I'll see if I can get someone from housing to verify. Or a student employee living in Somers

**Comment by rdelaloy** [comment]
You might just text Ty. She works on the Vern and took the photos so she probably knows which is which.

**Comment by qbaron** [comment]
Ty confirmed which images are which and I have updated the website accordingly
