### ISSUE TITLE
the html behind individual fellowship pages is broken and needs future proofing

### ISSUE THREAD

**Issue by sahiti-enjeti** [gwu-libraries/lai-drupal#8]
Individual fellowship pages are missing classes and IDs that would allow for styling things like "Eligibility" "Period of Study" and "Application" section headers. The code currently temporarily secures the section headers; however, there are no ID's or classes associated with the first `<div>` and since the CSS relies on the first `<div>` there needs to be defined classes and IDs. When changes are made, the styling will be affected and users will not be able to differentiate between the bullet points and headers on the page. 

Drupal adds in different classes for field labels - however, for fellowship pages this is not the case. More investigation is needed so the code for section headers can be more secure and not affected by CSS changes.

**Comment by maxstarkenburg** [comment]
Closing this here as it's being handled in the academiccommons-theme repo.
